---
# tasks file for nginx_site

    - name: Creates conf directory for Nginx container
      file:
       path: /$HOME/"{{ user }}"/web-app/conf
       state: directory

    - name: Copy nginx.conf
      template:
        src: nginx.conf.j2
        dest: /$HOME/"{{ user }}"/web-app/nginx.conf

    - name: Apply default site
      template:
        src: default.conf.j2
        dest: /$HOME/"{{ user }}"/web-app/conf/default.conf

    - name: Install Nginx container
      docker_container:
        name: web_nginx
        state: started
        image: nginx:latest
        pull: true
        recreate: yes
        ports:
         - 10002:80
        networks:
          - name: "{{ docker_network_name }}"
        volumes:
          - /$HOME/"{{ user }}"/web-app/conf/default.conf:/etc/nginx/conf.d/default.conf
          - /$HOME/"{{ user }}"/web-app/nginx.conf:/etc/nginx/nginx.conf

    - name: enable 80 port
      firewalld:
        zone: public
        port: 80/tcp
        permanent: true
        state: enabled

    - name: enable 443 port
      firewalld:
        zone: public
        port: 443/tcp
        permanent: true
        state: enabled