- name: Config all
  hosts: centos
  user: jenkins-agent
  gather_facts: yes
  become: yes
  vars_files:
    - ./global_vars/vars.yml

  tasks:

  #  - include_role:
  #      name: docker
#
  #  - name: Configure nginx balancer using role
  #    import_role:
  #      name: web


    - name: Configure nginx balancer using role
      import_role:
        name: nginx