- name: Config all
  hosts: centos
  user: jenkins-agent
  gather_facts: yes
  become: yes
  vars_files:
    - ./global_vars/vars.yml

  tasks:

  #  - name: Configure docker using role
  #    import_role:
  #      name: docker
  #    vars:
  #      ansible_python_interpreter: /usr/bin/python2  
 
   # - name: Configure web app using role
   #   import_role:
   #     name: web
   #   vars:
   #   #  ansible_python_interpreter: /usr/bin/python2.7


    - name: Configure nginx balancer using role
      import_role:
        name: nginx