---

####start containers

    - name: Delete a network, disconnecting all containers
      docker_network:
        name: "{{ docker_network_name }}"
        state: absent
        force: yes

    - name: Prune unused networks
      docker_prune:
        networks: yes

    - name: Create a network
      docker_network:
        name: "{{ docker_network_name }}"
        driver: bridge

    - name: Create my basic list of containers to stop
      set_fact:
        replicas:
          - port: "{{ port_1 }}"
            container: "{{ service_1 }}"
          - port: "{{ port_2 }}"
            container: "{{ service_2 }}"
          - port: "{{ port_3 }}"
            container: "{{ service_3 }}"

    - name: run containers
      docker_container:
        name: "{{ item.container }}"
        state: started
        image: "{{ docker_image }}"
        pull: true
        recreate: yes
        expose:
         - "{{ item.port }}"
        env:
          FLASK_RUN_PORT: "{{ item.port }}"
        networks:
          - name: "{{ docker_network_name }}"
      with_items: "{{ replicas }}"
